apiVersion: apps/v1
kind: Deployment
metadata:
  name: categories
  namespace: vitzi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: categories
  template:
    metadata:
      labels:
        app: categories
    spec:
      containers:
        - name: categories
          image: vitzi/categories:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
            - name: env
              value: dev
