apiVersion: v1
kind: Service
metadata:
  name: category-service
  namespace: vitzi
spec:
  type: LoadBalancer
  selector:
    app: categories
  ports:
    - name: http
      port: 80
      targetPort: 8080
